SELECT ANO_EJE, SEC_EJEC, PROYECTO_SNIP,FUENTE_FINANC,ACT_PROY,ID_CLASIFICADOR,
PROYECTO_SNIP+' '+PROYECTO_SNIP_NOMBRE AS PROYECTO_SNIP_NOMBRE,
FUENTE_FINANC+' '+FUENTE_FINANC_NOMBRE AS FUENTE_FINANC_NOMBRE, 
'2.'+CATEGORIA_GASTO+' '+GENERICA+'.'+SUBGENERICA+SUBGENERICA_DET+'.'+ESPECIFICA+ESPECIFICA_DET+' '+ESPECIFICA_DET_NOMBRE AS ESPECIFICA_DET_NOMBRE,
SUM(CASE WHEN MES_EJE<>'00'AND FASE='C' THEN EJECUCION ELSE 0 END) AS TOTAL_EJECUTADO,
SUM(CASE WHEN MES_EJE='01' AND FASE='C' THEN EJECUCION ELSE 0 END) AS ENERO,
SUM(CASE WHEN MES_EJE='02' AND FASE='C' THEN EJECUCION ELSE 0 END) AS FEBRERO,
SUM(CASE WHEN MES_EJE='03' AND FASE='C' THEN EJECUCION ELSE 0 END) AS MARZO,
SUM(CASE WHEN MES_EJE='04' AND FASE='C' THEN EJECUCION ELSE 0 END) AS ABRIL,
SUM(CASE WHEN MES_EJE='05' AND FASE='C' THEN EJECUCION ELSE 0 END) AS MAYO,
SUM(CASE WHEN MES_EJE='06' AND FASE='C' THEN EJECUCION ELSE 0 END) AS JUNIO,
SUM(CASE WHEN MES_EJE='07' AND FASE='C' THEN EJECUCION ELSE 0 END) AS JULIO,
SUM(CASE WHEN MES_EJE='08' AND FASE='C' THEN EJECUCION ELSE 0 END) AS AGOSTO,
SUM(CASE WHEN MES_EJE='09' AND FASE='C' THEN EJECUCION ELSE 0 END) AS SETIEMBRE,
SUM(CASE WHEN MES_EJE='10' AND FASE='C' THEN EJECUCION ELSE 0 END) AS OCTUBRE,
SUM(CASE WHEN MES_EJE='11' AND FASE='C' THEN EJECUCION ELSE 0 END) AS NOVIEMBRE,
SUM(CASE WHEN MES_EJE='12' AND FASE='C' THEN EJECUCION ELSE 0 END) AS DICIEMBRE
from dbo.infoReg_ejecucion_2009 
WHERE 
ANO_EJE='2012' AND
SEC_EJEC='001335' 
GROUP BY ANO_EJE,SEC_EJEC,ACT_PROY, ACT_PROY_NOMBRE,PROYECTO_SNIP,PROYECTO_SNIP_NOMBRE,FUENTE_FINANC,FUENTE_FINANC_NOMBRE,ID_CLASIFICADOR,CATEGORIA_GASTO,GENERICA,SUBGENERICA,SUBGENERICA_DET,ESPECIFICA,ESPECIFICA_DET,ESPECIFICA_DET_NOMBRE  
