SELECT ANO_EJE, SEC_EJEC, SEC_FUNC ,
PROGRAMA_PPTO+'.'+ACT_PROY+'.'+COMPONENTE+' '+ COMPONENTE_NOMBRE+' '+FUNCION+'.'+PROGRAMA+'.'+SUB_PROGRAMA AS SEC_FUNC_NOMBRE,
'META:'+META+'-'+FINALIDAD+' '+FINALIDAD_NOMBRE+', '+UNIDAD_MEDIDA_NOMBRE+' '+cast(CANTIDAD AS VARCHAR(18))+', '+DEPARTAMENTO_NOMBRE+', '+PROVINCIA_NOMBRE+', '+DISTRITO_NOMBRE DESCRIPCION_META,
FUENTE_FINANC+' '+FUENTE_FINANC_NOMBRE AS FUENTE_FINANC_NOMBRE ,
'2.'+GENERICA+'.'+SUBGENERICA+SUBGENERICA_DET+'.'+ESPECIFICA+ESPECIFICA_DET+' '+ESPECIFICA_DET_NOMBRE AS CLASIFICADOR,
SUM(CASE WHEN MES_EJE='00' THEN PIA ELSE 0 END) AS PIA,
SUM(CASE WHEN MES_EJE='00' THEN MODIFICACION ELSE 0 END) AS MODIFICACION,
SUM(CASE WHEN MES_EJE='00' THEN PIM ELSE 0 END) AS PIM,
SUM(CASE WHEN MES_EJE='00' THEN COMPROMETIDO_ANUAL ELSE 0 END) AS COMPROMETIDO_ANUAL,
SUM(CASE WHEN MES_EJE='00' THEN PIM-COMPROMETIDO_ANUAL ELSE 0 END) AS SALDO_PIM_COMPROMETIDO,
SUM(CASE WHEN MES_EJE<>'00'AND FASE='C' THEN EJECUCION ELSE 0 END) AS EJECUCION,
SUM(CASE WHEN MES_EJE='01' AND FASE='C' THEN EJECUCION ELSE 0 END) AS ENERO,
SUM(CASE WHEN MES_EJE='02' AND FASE='C' THEN EJECUCION ELSE 0 END) AS FEBRERO,
SUM(CASE WHEN MES_EJE='03' AND FASE='C' THEN EJECUCION ELSE 0 END) AS MARZO,
SUM(CASE WHEN MES_EJE='04' AND FASE='C' THEN EJECUCION ELSE 0 END) AS ABRIL,
SUM(CASE WHEN MES_EJE='05' AND FASE='C' THEN EJECUCION ELSE 0 END) AS MAYO,
SUM(CASE WHEN MES_EJE='06' AND FASE='C' THEN EJECUCION ELSE 0 END) AS JUNIO,
SUM(CASE WHEN MES_EJE='07' AND FASE='C' THEN EJECUCION ELSE 0 END) AS JULIO,
SUM(CASE WHEN MES_EJE='08' AND FASE='C' THEN EJECUCION ELSE 0 END) AS AGOSTO,
SUM(CASE WHEN MES_EJE='09' AND FASE='C' THEN EJECUCION ELSE 0 END) AS SETIEMBRE,
SUM(CASE WHEN MES_EJE='10' AND FASE='C' THEN EJECUCION ELSE 0 END) AS OCTUBRE,
SUM(CASE WHEN MES_EJE='11' AND FASE='C' THEN EJECUCION ELSE 0 END) AS NOVIEMBRE,
SUM(CASE WHEN MES_EJE='12' AND FASE='C' THEN EJECUCION ELSE 0 END) AS DICIEMBRE,
SUM(CASE WHEN MES_EJE='00' THEN PIM ELSE 0 END)-SUM(CASE WHEN MES_EJE<>'00'AND FASE='C' THEN EJECUCION ELSE 0 END)  AS SALDO_EJECUCION
from dbo.infoReg_ejecucion_2009 
WHERE 
ANO_EJE='2012' AND
SEC_EJEC='001335' 
group by ano_eje, sec_ejec, SEC_FUNC,PROGRAMA_PPTO,ACT_PROY,COMPONENTE,COMPONENTE_NOMBRE,
META,FINALIDAD,FINALIDAD_NOMBRE,UNIDAD_MEDIDA,UNIDAD_MEDIDA_NOMBRE,CANTIDAD,DEPARTAMENTO,DEPARTAMENTO_NOMBRE,PROVINCIA,PROVINCIA_NOMBRE,DISTRITO,DISTRITO_NOMBRE,
	FUNCION,PROGRAMA,SUB_PROGRAMA,FUENTE_FINANC, FUENTE_FINANC_NOMBRE,
	GENERICA,SUBGENERICA,SUBGENERICA_DET,ESPECIFICA,ESPECIFICA_DET,ESPECIFICA_DET_NOMBRE
order by ano_eje, sec_ejec, SEC_FUNC,PROGRAMA_PPTO,ACT_PROY,COMPONENTE,COMPONENTE_NOMBRE,
META,FINALIDAD,FINALIDAD_NOMBRE,UNIDAD_MEDIDA,UNIDAD_MEDIDA_NOMBRE,DEPARTAMENTO,DEPARTAMENTO_NOMBRE,PROVINCIA,PROVINCIA_NOMBRE,DISTRITO,DISTRITO_NOMBRE,
	FUNCION,PROGRAMA,SUB_PROGRAMA,FUENTE_FINANC, FUENTE_FINANC_NOMBRE,
	GENERICA,SUBGENERICA,SUBGENERICA_DET,ESPECIFICA,ESPECIFICA_DET,ESPECIFICA_DET_NOMBRE

select *
from dbo.inforeg_ejecucion_2009 where sec_ejec='001335' and pia=0 and modificacion=0 and ano_eje='2012'



SELECT distinct PROGRAMA_PPTO+ACT_PROY+COMPONENTE+FUNCION+PROGRAMA+SUB_PROGRAMA ,
PROGRAMA_PPTO+'.'+ACT_PROY+'.'+COMPONENTE+' '+ COMPONENTE_NOMBRE+' '+FUNCION+'.'+PROGRAMA+'.'+SUB_PROGRAMA AS SEC_FUNC_NOMBRE
from dbo.infoReg_ejecucion_2009 
WHERE 
ANO_EJE='2012' AND
SEC_EJEC='001335' 
order by PROGRAMA_PPTO+ACT_PROY+COMPONENTE+FUNCION+PROGRAMA+SUB_PROGRAMA
